### ISSUE TITLE
DiscordAcePerms-master: Deferring connection...

### ISSUE THREAD

**Issue by TheKidCottons** [JaredScar/DiscordAcePerms#4]
Whenever I try and connect to the server, it gets stuck on 'DiscordAcePerms-master: Deferring connection...' Do you know why this is happening?

**Comment by OfficerBozza** [comment]
Having same issue.

**Comment by OfficerBozza** [comment]
#5 Managed to fix by updating __resource.lua to the newer fxmanifest.lua.

**Comment by JaredScar** [comment]
Updating the `__resource.lua` should not fix this issue. That issue is caused by a configuration issue. In other words, you made a mistake in the configuration file and need to fix it in order for this script to work. @TheKidCottons I am closing this because this is not a real issue, but on fault of your own.
